// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-gJv1RhhJDouYfO7O5QpRP2b8gPzvvM',
    appId: '1:318072354583:web:5fa952cb56df5561836952',
    messagingSenderId: '318072354583',
    projectId: 'kam-wala-app',
    authDomain: 'kam-wala-app.firebaseapp.com',
    storageBucket: 'kam-wala-app.firebasestorage.app',
    measurementId: 'G-4WN3R4E3M7',
    //add this for add post
    databaseURL: 'https://kam-wala-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB6u1Qa7QZlcV5RLoUvzwwp9jZUVUcmSM',
    appId: '1:318072354583:android:21218d34fe4fe4b6836952',
    messagingSenderId: '318072354583',
    projectId: 'kam-wala-app',
    storageBucket: 'kam-wala-app.firebasestorage.app',
    databaseURL:
        'https://kam-wala-app-default-rtdb.firebaseio.com', // ✅ add this
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMB7aYbwyFEximT1QtyJKMWwwxAoYRUsw',
    appId: '1:318072354583:ios:2e37c30479050d84836952',
    messagingSenderId: '318072354583',
    projectId: 'kam-wala-app',
    storageBucket: 'kam-wala-app.firebasestorage.app',
    iosBundleId: 'com.example.kamWalaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMB7aYbwyFEximT1QtyJKMWwwxAoYRUsw',
    appId: '1:318072354583:ios:2e37c30479050d84836952',
    messagingSenderId: '318072354583',
    projectId: 'kam-wala-app',
    storageBucket: 'kam-wala-app.firebasestorage.app',
    iosBundleId: 'com.example.kamWalaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW-gJv1RhhJDouYfO7O5QpRP2b8gPzvvM',
    appId: '1:318072354583:web:d8eac0e57577dd3c836952',
    messagingSenderId: '318072354583',
    projectId: 'kam-wala-app',
    authDomain: 'kam-wala-app.firebaseapp.com',
    storageBucket: 'kam-wala-app.firebasestorage.app',
    measurementId: 'G-8FSPD5ZWEH',
    //databaseURL: 'https://kam-wala-app.firebaseio.com',
  );
}
